name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - Cython
  - h5py
  - gxx_linux-64
  - neuron=*=mpi_*
  - pytest
  - mpi4py
  - MEAutility>=1.4.2
  - pip
  - pip:
    - '--editable=git+https://github.com/LFPy/LFPykit.git@master#egg=LFPykit'
