name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - c-compiler
  - cxx-compiler
  - pthread-stubs
  - mpi4py
  - sphinx_rtd_theme
  - numpydoc
  - m2r2
  - pip
  - pip:
